server:
  port: 8090
spring:
  application:
    name: "employees"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jba:
    show-sql: true
    hibernate:
      dbl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  profiles:
    active: qa
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: 3.0.0